[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
ranu_finance = "FJou9p7xKpTwGdH6aCjrGFexE9SHDJpuKntKjN7JL1U2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "devnet"
wallet = "./keys/user1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
